ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER groomer CASCADE;
CREATE USER groomer IDENTIFIED BY groomer2020;
GRANT NASTAVNIK TO groomer;
ALTER USER groomer DEFAULT TABLESPACE USERS QUOTA 400m ON USERS;
