INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 604.22, 1 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-12-24', 'YYYY-MM-DD'), 1 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2019-10-23', 'YYYY-MM-DD'), NULL, 1 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 605.64, 2 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-11-16', 'YYYY-MM-DD'), 2 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-12-09', 'YYYY-MM-DD'), TO_DATE('2019-10-05', 'YYYY-MM-DD'), 2 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2019-12-29', 'YYYY-MM-DD'), NULL, 2 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 993.3, 3 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 3 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 878.18, 4 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 4 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 556.27, 5 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 5 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 590.4, 6 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 6 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 406.05, 7 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 7 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 912.26, 8 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 8 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 546.67, 9 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 9 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 336.22, 10 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 10 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 876.55, 11 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 11 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 467.17, 12 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 12 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 372.79, 13 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 13 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 98.62, 14 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 14 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 963.64, 15 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 15 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 219.34, 16 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 16 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 705.8, 17 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 17 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 826.54, 18 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-12-26', 'YYYY-MM-DD'), 18 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2019-04-28', 'YYYY-MM-DD'), TO_DATE('2019-10-04', 'YYYY-MM-DD'), 18 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2020-03-11', 'YYYY-MM-DD'), NULL, 18 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2019-07-24', 'YYYY-MM-DD'), 877.74, 19 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-07-25', 'YYYY-MM-DD'), TO_DATE('2019-08-01', 'YYYY-MM-DD'), 736.89, 19 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-08-02', 'YYYY-MM-DD'), NULL, 652.28, 19 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 19 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 477.02, 20 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 20 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2019-06-25', 'YYYY-MM-DD'), 233.28, 21 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-06-26', 'YYYY-MM-DD'), NULL, 857.91, 21 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 21 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 998.36, 22 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 22 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2020-01-02', 'YYYY-MM-DD'), 675.33, 23 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2020-01-03', 'YYYY-MM-DD'), TO_DATE('2020-02-02', 'YYYY-MM-DD'), 680.95, 23 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2020-02-03', 'YYYY-MM-DD'), NULL, 287.13, 23 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 23 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 471.94, 24 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-07-26', 'YYYY-MM-DD'), 24 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-09-01', 'YYYY-MM-DD'), TO_DATE('2019-05-20', 'YYYY-MM-DD'), 24 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2020-05-01', 'YYYY-MM-DD'), NULL, 24 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 967.17, 25 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 25 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 775.26, 26 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 26 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 469.54, 27 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 27 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 723.65, 28 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 28 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 449.03, 29 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 29 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 848.58, 30 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 30 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 518.36, 31 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 31 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 881.29, 32 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 32 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 274.29, 33 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 33 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 836.84, 34 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 34 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 837.81, 35 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 35 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 391.68, 36 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 36 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 474.74, 37 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 37 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 935.64, 38 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 38 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 664.64, 39 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 39 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 759.39, 40 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 40 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 631.9, 41 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 41 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 57.19, 42 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 42 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 380.78, 43 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 43 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 620.22, 44 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 44 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 350.46, 45 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 45 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 970.36, 46 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 46 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2019-02-01', 'YYYY-MM-DD'), 623.31, 47 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-02-02', 'YYYY-MM-DD'), NULL, 400.94, 47 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 47 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 967.11, 48 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 48 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 384.9, 49 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 49 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 807.5, 50 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 50 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 123.27, 51 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 51 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-09-07', 'YYYY-MM-DD'), 508.26, 52 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-09-08', 'YYYY-MM-DD'), NULL, 463.22, 52 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 52 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 243.59, 53 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 53 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 575.45, 54 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 54 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2019-08-17', 'YYYY-MM-DD'), 868.8, 55 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-08-18', 'YYYY-MM-DD'), NULL, 722.28, 55 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 55 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 978.74, 56 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 56 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 997.87, 57 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 57 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-05-24', 'YYYY-MM-DD'), 59.43, 58 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-25', 'YYYY-MM-DD'), NULL, 943.04, 58 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 58 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 597.74, 59 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 59 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 25.17, 60 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-06-09', 'YYYY-MM-DD'), 60 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-09-22', 'YYYY-MM-DD'), TO_DATE('2018-12-01', 'YYYY-MM-DD'), 60 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2019-12-07', 'YYYY-MM-DD'), NULL, 60 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 574.09, 61 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 61 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 247.95, 62 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 62 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 526.76, 63 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 63 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 70.03, 64 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 64 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 956.69, 65 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 65 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 992.8, 66 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-06-22', 'YYYY-MM-DD'), 66 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-07-12', 'YYYY-MM-DD'), TO_DATE('2018-11-17', 'YYYY-MM-DD'), 66 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2019-04-14', 'YYYY-MM-DD'), NULL, 66 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 413.52, 67 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-08-27', 'YYYY-MM-DD'), 67 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-11-12', 'YYYY-MM-DD'), TO_DATE('2019-02-15', 'YYYY-MM-DD'), 67 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2020-03-31', 'YYYY-MM-DD'), NULL, 67 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 243.28, 68 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2019-04-09', 'YYYY-MM-DD'), 68 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2019-05-13', 'YYYY-MM-DD'), TO_DATE('2019-12-05', 'YYYY-MM-DD'), 68 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2020-02-22', 'YYYY-MM-DD'), NULL, 68 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 345.59, 69 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 69 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 62.19, 70 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 70 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 992.82, 71 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 71 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2019-07-02', 'YYYY-MM-DD'), 827.85, 72 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-07-03', 'YYYY-MM-DD'), TO_DATE('2019-10-14', 'YYYY-MM-DD'), 282.75, 72 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-10-15', 'YYYY-MM-DD'), NULL, 293.84, 72 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 72 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 899.01, 73 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 73 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 912.07, 74 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 74 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-12-28', 'YYYY-MM-DD'), 336.86, 75 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-12-29', 'YYYY-MM-DD'), TO_DATE('2020-01-13', 'YYYY-MM-DD'), 21.62, 75 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2020-01-14', 'YYYY-MM-DD'), NULL, 553.12, 75 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 75 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 334.47, 76 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 76 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 568.29, 77 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 77 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 241.44, 78 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 78 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 868.73, 79 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 79 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 891.25, 80 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 80 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 400.74, 81 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 81 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 727.18, 82 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 82 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 905.97, 83 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 83 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2019-08-08', 'YYYY-MM-DD'), 928.35, 84 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2019-08-09', 'YYYY-MM-DD'), TO_DATE('2020-03-02', 'YYYY-MM-DD'), 591.09, 84 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2020-03-03', 'YYYY-MM-DD'), NULL, 254.43, 84 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 84 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 129.15, 85 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 85 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 997.83, 86 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 86 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 558.11, 87 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), TO_DATE('2018-07-14', 'YYYY-MM-DD'), 87 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2019-07-29', 'YYYY-MM-DD'), NULL, 87 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 18.66, 88 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 88 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 810.89, 89 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 89 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 916.92, 90 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 90 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 44.69, 91 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 91 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 88.16, 92 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 92 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 652.29, 93 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 93 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 569.66, 94 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 94 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 21.06, 95 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 95 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 595.09, 96 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 96 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 138.22, 97 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 97 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 111.34, 98 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 98 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 454.77, 99 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 99 );
INSERT INTO promjenaproizvoda (tip, od, do, iznos, proizvod_prz_id) VALUES ('Cijena', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 523.74, 100 );
INSERT INTO promjenaproizvoda (tip, od, do, proizvod_prz_id) VALUES ('Ponuda', TO_DATE('2018-05-11', 'YYYY-MM-DD'), NULL, 100 );
