SET DEFINE OFF

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('GROENENDAEL', 1, 2, 'GROENENDAEL', 'GROENENDAEL');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LAEKENOIS', 2, 2, 'LAEKENOIS', 'LAEKENOIS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MALINOIS', 3, 2, 'MALINOIS', 'MALINOIS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('TERVUEREN', 4, 2, 'TERVUEREN', 'TERVUEREN');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('DOUBLE COAT', 5, 10, 'DVOSTRUKA DLAKA', 'DVOSTRUKA DLAKA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG AND HARSH OUTER COAT', 6, 10, 'DUGA I GRUBA DLAKA', 'DUGA I GRUBA DLAKA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('FAWN', 7, 21, 'ŽUTOSMEĐI', 'ŽUTOSMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 8, 21, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLUE-MERLE', 9, 21, 'PLAVO-MERLE', 'PLAVO-MERLE');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('ASH COLOURED (BLUE GREY)', 10, 21, 'PEPELJASTI', 'PEPELJASTI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BROWN', 11, 21, 'SMEĐI', 'SMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('WHITE', 12, 21, 'BIJELI', 'BIJELI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PEARL-WHITE', 13, 22, 'BISERNO BIJELI', 'BISERNO BIJELI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 14, 22, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('GREY IN VARIOUS SHADES', 15, 23, 'SIVI U RAZNIM NIJANSAMA', 'SIVI U RAZNIM NIJANSAMA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 16, 23, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('FAWN (FAKÓ). PRIMARY COLOURS: RED, YELLOW, CREAM', 17, 23, 'ŽUTOSMEĐI', 'ŽUTOSMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('WHITE', 18, 23, 'BIJELI', 'BIJELI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SHORT-HAIRED', 19, 35, 'KRATKODLAKI', 'KRATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG-HAIRED', 20, 35, 'DUGODLAKI', 'DUGODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SHORT-HAIRED', 21, 38, 'KRATKODLAKI', 'KRATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG-HAIRED', 22, 38, 'DUGODLAKI', 'DUGODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('ROUGH-HAIRED', 23, 38, 'OŠTRODLAKI', 'OŠTRODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK WITH RUST RED CLEARLY DEFINED AND CLEAN MARKINGS', 24, 47, 'CRNI S RĐAVO CRVENIM JASNO DEFINIRANIM I ČISTIM OZNAKAMA', 'CRNI S RĐAVO CRVENIM JASNO DEFINIRANIM I ČISTIM OZNAKAMA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BROWN WITH RUST RED CLEARLY DEFINED AND CLEAN MARKINGS', 25, 47, 'SMEĐI S RĐAVO CRVENIM JASNO DEFINIRANIM I ČISTIM OZNAKAMA', 'SMEĐI S RĐAVO CRVENIM JASNO DEFINIRANIM I ČISTIM OZNAKAMA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SELF COLOURED: DEER RED, REDDISH-BROWN TO DARK RED BROWN', 26, 48, 'JEDNOBOJAN: JELENJE CRVENA, CRVENKASTO-SMEĐA DO TAMNO CERVNO SMEĐE', 'JEDNOBOJAN: JELENJE CRVENA, CRVENKASTO-SMEĐA DO TAMNO CERVNO SMEĐE');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK AND TAN', 27, 48, 'CRNI I TAMNO SMEĐI', 'CRNI I TAMNO SMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SELF COLOURED: DEER RED, REDDISH-BROWN TO DARK RED BROWN', 28, 49, 'JEDNOBOJAN: JELENJE CRVENA, CRVENKASTO-SMEĐA DO TAMNO CERVNO SMEĐE', 'JEDNOBOJAN: JELENJE CRVENA, CRVENKASTO-SMEĐA DO TAMNO CERVNO SMEĐE');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK AND TAN', 29, 49, 'CRNI I TAMNO SMEĐI', 'CRNI I TAMNO SMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PEPPER AND SALT', 30, 50, 'BIBER I SOL', 'BIBER I SOL');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PURE BLACK WITH BLACK UNDERCOAT', 31, 50, 'ČISTO CRNI SA CRNOM PODDLAKOM', 'ČISTO CRNI SA CRNOM PODDLAKOM');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PEPPER AND SALT', 32, 51, 'BIBER I SOL', 'BIBER I SOL');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PURE BLACK WITH BLACK UNDERCOAT', 33, 51, 'ČISTO CRNI SA CRNOM PODDLAKOM', 'ČISTO CRNI SA CRNOM PODDLAKOM');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK AND SILVER', 34, 51, 'CRNI I SREBRNI', 'CRNI I SREBRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PURE WHITE WITH WHITE UNDERCOAT', 35, 51, 'ČISTO BIJELI SA BIJELOM PODDLAKOM', 'ČISTO BIJELI SA BIJELOM PODDLAKOM');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PEPPER AND SALT', 36, 52, 'BIBER I SOL', 'BIBER I SOL');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PURE BLACK WITH BLACK UNDERCOAT', 37, 52, 'ČISTO CRNI SA CRNOM PODDLAKOM', 'ČISTO CRNI SA CRNOM PODDLAKOM');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('FAWN', 38, 60, 'ŽUTOSMEĐI', 'ŽUTOSMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BRINDLE', 39, 60, 'TIGRAST', 'TIGRAST');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('FAWN', 40, 61, 'ŽUTOSMEĐI', 'ŽUTOSMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 41, 61, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLUE', 42, 61, 'PLAVI', 'PLAVI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 43, 74, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('WHITE AND BLACK', 44, 74, 'BIJELI I CRNI', 'BIJELI I CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BROWN', 45, 74, 'SMEĐI', 'SMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK-GOLD', 46, 76, 'CRNO-ZLATNI', 'CRNO-ZLATNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 47, 76, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLOND', 48, 76, 'PLAVI', 'PLAVI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SHORT-HAIRED', 49, 82, 'KRATKODLAKI', 'KRATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG-HAIRED', 50, 82, 'DUGODLAKI', 'DUGODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SHORT-HAIRED', 51, 90, 'KRATKODLAKI', 'KRATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG-HAIRED', 52, 90, 'DUGODLAKI', 'DUGODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('STANDARD', 53, 131, 'STANDARDNI', 'STANDARDNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MINIATURE', 54, 131, 'MINIJATURNI', 'MINIJATURNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('RABBIT DACHSHUND', 55, 131, 'ZEČJI JAZAVIČAR', 'ZEČJI JAZAVIČAR');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('KEESHOND (WOLFSPITZ)', 56, 153, 'VUČJI ŠPIC', 'VUČJI ŠPIC');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('GIANT SPITZ', 57, 153, 'GIGANTSKI ŠPIC', 'GIGANTSKI ŠPIC');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MEDIUM SIZE SPITZ', 58, 153, 'SRENJI ŠPIC', 'SRENJI ŠPIC');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MINIATURE SPITZ', 59, 153, 'MINIJATURNI ŠOIC', 'MINIJATURNI ŠOIC');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('POMERANIAN', 60, 153, 'POMERANSKI', 'POMERANSKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MINIATURE', 61, 169, 'MINIJATURNI', 'MINIJATURNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('INTERMEDIATE', 62, 169, 'SREDNJI', 'SREDNJI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('STANDARD', 63, 169, 'STANDARDNI', 'STANDARDNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LARGE', 64, 170, 'VELIKI', 'VELIKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MEDIUM-SIZED', 65, 170, 'SREDNJI', 'SREDNJI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MINIATURE', 66, 170, 'MINIJATURNI', 'MINIJATURNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMALL', 67, 172, 'MALI', 'MALI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MEDIUM-SIZED', 68, 172, 'SREDNJI', 'SREDNJI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LARGE', 69, 172, 'VELIKI', 'VELIKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMOOTH-HAIRED', 70, 174, 'GLATKODLAKI', 'GLATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('ROUGH-HAIRED', 71, 174, 'OŠTRODLAKI', 'OŠTRODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BERNESE HOUND', 72, 229, 'BERNSKI LOVAČKI PAS', 'BERNSKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('JURA HOUND', 73, 229, 'JURSKI LOVAČKI PAS', 'JURSKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LUCERNE HOUND', 74, 229, 'LUCERNSKI LOVAČKI PAS', 'LUCERNSKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SCHWYZ HOUND', 75, 229, 'ŠVISKI LOVAČKI PAS', 'ŠVISKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMALL JURA HOUND', 76, 240, 'MALI JURSKI LOVAČKI PAS', 'MALI JURSKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMALL SCHWYZ HOUND', 77, 240, 'MALI ŠVISKI LOVAČKI PAS', 'MALI ŠVISKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMALL BERNESE HOUND', 78, 240, 'MALI BERNSKI LOVAČKI PAS', 'MALI BERNSKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMALL LUCERNE HOUND', 79, 240, 'MALI LUCERNSKI LOVAČKI PAS', 'MALI LUCERNSKI LOVAČKI PAS');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SHORT-HAIRED', 80, 257, 'KRATKODLAKI', 'KRATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG-HAIRED', 81, 257, 'DUGODLAKI', 'DUGODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('WHITE-ORANGE', 82, 260, 'NARANČASTO-BIJELI', 'NARANČASTO-BIJELI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('CHESTNUT ROAN', 83, 260, 'KESTANASTO CRVENKASTO-SIV', 'KESTANASTO CRVENKASTO-SIV');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SOLID COLOURS', 84, 290, 'ČISTOBOJAN', 'ČISTOBOJAN');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PARTICOLOURS (BICOLOURS, TRICOLOURS, ROANS)', 85, 290, 'VIŠEBOJAN (DVOBOJAN, TROBOJAN, CRVENKASTO-SIV)', 'VIŠEBOJAN (DVOBOJAN, TROBOJAN, CRVENKASTO-SIV)');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 86, 296, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('ANY SOLID COLOUR OTHER THAN BLACK (ASCOB)', 87, 296, 'SVE ČISTE BOJE OSIM CRNE', 'SVE ČISTE BOJE OSIM CRNE');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PARTI-COLOUR', 88, 296, 'VIŠEBOJAN', 'VIŠEBOJAN');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG AND WAVY', 89, 300, 'DUGI I TALASASTI', 'DUGI I TALASASTI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SHORTER AND CURLY', 90, 300, 'KRATKI I KOVRČAVI', 'KRATKI I KOVRČAVI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('STANDARD', 91, 310, 'STANDARDNI', 'STANDARDNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MEDIUM SIZE', 92, 310, 'SREDNJI', 'SREDNJI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('MINIATURE', 93, 310, 'MINIJATURNI', 'MINIJATURNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('TOY', 94, 310, 'PATULJASTI', 'PATULJASTI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('HAIRLESS', 95, 314, 'BEZDLAKI', 'BEZDLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('POWDER PUFF', 96, 314, 'PRAŠKAST', 'PRAŠKAST');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONG-HAIRED', 97, 319, 'DUGODLAKI', 'DUGODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMOOTH-HAIRED', 98, 319, 'GLATKODLAKI', 'GLATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK AND TAN', 99, 320, 'CRNI I ŽUTOSMEĐI', 'CRNI I ŽUTOSMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('RUBY', 100, 320, 'RUBINSKI', 'RUBINSKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLENHEIM', 101, 320, 'BLENHEIMSKI', 'BLENHEIMSKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('TRICOLOUR', 102, 320, 'TROBOJAN', 'TROBOJAN');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK AND TAN', 103, 321, 'CRNI I ŽUTOSMEĐI', 'CRNI I ŽUTOSMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('RUBY', 104, 321, 'RUBINSKI', 'RUBINSKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLENHEIM', 105, 321, 'BLENHEIMSKI', 'BLENHEIMSKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('TRICOLOUR', 106, 321, 'TROBOJAN', 'TROBOJAN');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PAPILLON - WITH ERECT EARS', 107, 324, 'PAPILON - SA USPRAVNIM UŠIMA', 'PAPILON - SA USPRAVNIM UŠIMA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('PHALČNE - WITH DROOPING EARS', 108, 324, 'PHALČNE - SA PADAJUĆIM UŠIMA', 'PHALČNE - SA PADAJUĆIM UŠIMA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMOOTH-HAIRED', 109, 325, 'GLATKODLAKI', 'GLATKODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('LONGHAIRED', 110, 325, 'DUGODLAKI', 'DUGODLAKI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SILVER', 111, 327, 'SREBRNI', 'SREBRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('APRICOT', 112, 327, 'MARELICA', 'MARELICA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('FAWN', 113, 327, 'ŽUTOSMEĐI', 'ŽUTOSMEĐI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('BLACK', 114, 327, 'CRNI', 'CRNI');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('UNIFORMLY FAWN, BRINDLED OR NOT, OR WITH LIMITED WHITE PATCHING', 115, 328, 'UNIFORMNO ŽUTOSMEĐI, TIGRAST ILI NE, ILI SA OGRANIČENIM BIJELIM FLEKAMA', 'UNIFORMNO ŽUTOSMEĐI, TIGRAST ILI NE, ILI SA OGRANIČENIM BIJELIM FLEKAMA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('FAWN, BRINDLED OR NOT, WITH MEDIUM OR PREDOMINANT PATCHING', 116, 328, 'ŽUTOSMEĐI, TIGRAST ILI NE, SA SREDNJE ILI PREDOMINANTNIM FLEKAMA', 'ŽUTOSMEĐI, TIGRAST ILI NE, SA SREDNJE ILI PREDOMINANTNIM FLEKAMA');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('FRINGED', 117, 331, 'ČIPKAST', 'RESAST');

INSERT INTO VARIJANTA (NAZIV, VAR_ID, FCI_PAS_FPS_ID, SRPSKI_NAZIV, HRVATSKI_NAZIV) 
VALUES ('SMOOTH', 118, 331, 'GLATKI', 'GLATKI');

-- Import Data into table VARIJANTA from file C:\coderepos\groom\data_prep\fci\varijante.xlsx . Task successful and sent to worksheet.
