INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (1, 'Na poslu', '+385 53 350 560');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (1, 'Facebook', 'www.facebook.com/goosnarghpunctual');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (1, 'Kućni', '+385 94 240 621');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (1, 'Poslovni mobitel', '+385 92 725 9102');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (1, 'Skype', 'pigfinger45');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (1, 'Mobitel', '+385 95 795 4621');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (1, 'Poslovna e-mail adresa', 'extensionstribe@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Skype', 'kokoambulance52');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Instagram', 'www.instagram.com/leonzone');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Poslovna e-mail adresa', 'priesttrash@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Mobitel', '+385 99 726 3280');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Fax', '+385 94 828 971');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Na poslu', '+385 40 581 935');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Facebook', 'www.facebook.com/iridescentkarma');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Poslovni mobitel', '+385 99 393 5735');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (2, 'Kućni', '+385 44 526 388');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Poslovni mobitel', '+385 92 251 1265');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Fax', '+385 45 201 272');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Instagram', 'www.instagram.com/humormongoose');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Skype', 'bulbsoverwrite57');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Poslovna e-mail adresa', 'morainefetch@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Privatna e-mail adresa', 'keepreceipt@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Kućni', '+385 57 503 298');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (4, 'Facebook', 'www.facebook.com/antennabreast');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (5, 'Poslovni mobitel', '+385 92 600 2142');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (5, 'Na poslu', '+385 83 920 594');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (5, 'Facebook', 'www.facebook.com/carbonlaunching');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (7, 'Skype', 'nastilysad37');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (7, 'Instagram', 'www.instagram.com/ponymolecular');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (7, 'Mobitel', '+385 99 801 3322');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (7, 'Poslovna e-mail adresa', 'yardbradford@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (8, 'Skype', 'nenderquicksand75');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (8, 'Privatna e-mail adresa', 'gaurscandale@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (8, 'Na poslu', '+385 52 380 388');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (8, 'Facebook', 'www.facebook.com/ponymolecular');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (8, 'Instagram', 'www.instagram.com/cheekstercalifornia');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (8, 'Kućni', '+385 47 247 464');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (8, 'Poslovna e-mail adresa', 'anxietymogul@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (9, 'Facebook', 'www.facebook.com/lickingjoining');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (9, 'Poslovni mobitel', '+385 91 691 8898');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (9, 'Privatna e-mail adresa', 'sagapoles@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (9, 'Kućni', '+385 90 322 134');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (9, 'Instagram', 'www.instagram.com/contortdice');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (10, 'Mobitel', '+385 92 265 6413');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (11, 'Facebook', 'www.facebook.com/breechingvholes');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (11, 'Mobitel', '+385 97 333 6873');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (11, 'Kućni', '+385 29 270 201');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (11, 'Poslovna e-mail adresa', 'slidingsnarling@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (11, 'Privatna e-mail adresa', 'cookiearsenic@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (12, 'Mobitel', '+385 97 997 5348');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (12, 'Na poslu', '+385 40 693 333');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (12, 'Skype', 'tablessandbag55');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (12, 'Facebook', 'www.facebook.com/pigfinger');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (12, 'Kućni', '+385 90 999 605');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (12, 'Fax', '+385 10 731 731');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Kućni', '+385 57 563 304');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Mobitel', '+385 99 974 3424');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Skype', 'rawgabbitcondense33');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Facebook', 'www.facebook.com/scuffrod');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Privatna e-mail adresa', 'nenderquicksand@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Fax', '+385 40 723 955');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Poslovni mobitel', '+385 92 298 6805');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (13, 'Instagram', 'www.instagram.com/quaintcheck');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (15, 'Kućni', '+385 86 961 688');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (15, 'Privatna e-mail adresa', 'burritoraking@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (15, 'Poslovni mobitel', '+385 92 846 8743');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (16, 'Privatna e-mail adresa', 'tablessandbag@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (16, 'Poslovni mobitel', '+385 99 990 4779');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (18, 'Instagram', 'www.instagram.com/rancidityxenotime');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (18, 'Kućni', '+385 60 343 599');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (18, 'Poslovni mobitel', '+385 92 384 7184');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (18, 'Privatna e-mail adresa', 'astutedowry@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (18, 'Fax', '+385 34 100 180');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (18, 'Mobitel', '+385 99 469 5106');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (18, 'Na poslu', '+385 34 971 565');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (20, 'Kućni', '+385 34 588 942');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (20, 'Facebook', 'www.facebook.com/nithpucker');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (20, 'Privatna e-mail adresa', 'handemphasis@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (20, 'Skype', 'ferocitycrate55');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (20, 'Na poslu', '+385 57 924 899');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (21, 'Poslovna e-mail adresa', 'cartieracorn@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (21, 'Poslovni mobitel', '+385 91 509 7677');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (21, 'Fax', '+385 90 666 850');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (21, 'Instagram', 'www.instagram.com/minorgnarly');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (21, 'Mobitel', '+385 98 542 9739');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (21, 'Kućni', '+385 22 781 915');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (22, 'Facebook', 'www.facebook.com/fibblesnitchey');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (22, 'Poslovna e-mail adresa', 'tarbertfarrum@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (22, 'Fax', '+385 48 652 831');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (23, 'Fax', '+385 31 368 931');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (24, 'Poslovni mobitel', '+385 98 779 2730');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (24, 'Na poslu', '+385 31 641 161');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (24, 'Privatna e-mail adresa', 'chicagoproblems@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (25, 'Instagram', 'www.instagram.com/cosinesstraggler');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (25, 'Poslovni mobitel', '+385 97 415 3576');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (25, 'Fax', '+385 17 664 517');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (25, 'Na poslu', '+385 46 309 375');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (25, 'Mobitel', '+385 97 804 1194');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (25, 'Skype', 'raviolitickets96');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (25, 'Poslovna e-mail adresa', 'rustproofpester@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Poslovni mobitel', '+385 92 278 3320');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Privatna e-mail adresa', 'magneticfrancium@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Fax', '+385 48 956 985');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Facebook', 'www.facebook.com/pauperrevolt');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Instagram', 'www.instagram.com/swearsloth');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Poslovna e-mail adresa', 'leonzone@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Skype', 'pigfinger93');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Mobitel', '+385 95 226 7111');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (26, 'Kućni', '+385 99 197 375');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (28, 'Kućni', '+385 13 701 129');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (28, 'Poslovna e-mail adresa', 'writergenders@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (29, 'Poslovni mobitel', '+385 99 686 4527');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (30, 'Na poslu', '+385 73 167 572');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (30, 'Instagram', 'www.instagram.com/nastilysad');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (31, 'Facebook', 'www.facebook.com/exactingbrushes');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (31, 'Poslovna e-mail adresa', 'anxietymogul@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (31, 'Kućni', '+385 76 746 946');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (31, 'Privatna e-mail adresa', 'rawgabbitcondense@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (31, 'Instagram', 'www.instagram.com/sharkslurp');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (31, 'Mobitel', '+385 98 849 7942');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (31, 'Poslovni mobitel', '+385 92 585 4366');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (32, 'Na poslu', '+385 32 512 964');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (32, 'Mobitel', '+385 99 389 4215');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (32, 'Poslovna e-mail adresa', 'pigfinger@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Skype', 'severityspectacle88');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Poslovna e-mail adresa', 'bundevaraamuse@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Instagram', 'www.instagram.com/goosnarghpunctual');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Mobitel', '+385 92 917 5250');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Na poslu', '+385 35 169 723');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Fax', '+385 98 696 802');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Poslovni mobitel', '+385 91 695 4547');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (33, 'Privatna e-mail adresa', 'argueradde@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (34, 'Privatna e-mail adresa', 'landminefencing@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (35, 'Privatna e-mail adresa', 'pignutmega@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (35, 'Facebook', 'www.facebook.com/extensionstribe');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (36, 'Facebook', 'www.facebook.com/gentlemanyorkshire');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (36, 'Privatna e-mail adresa', 'scuffrod@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (36, 'Poslovna e-mail adresa', 'residencesdependable@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (36, 'Mobitel', '+385 92 945 1360');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (36, 'Fax', '+385 44 591 491');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (36, 'Skype', 'spacerssake80');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (36, 'Poslovni mobitel', '+385 97 162 2630');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (37, 'Poslovna e-mail adresa', 'hurrywanting@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (37, 'Skype', 'unratedcivic94');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Kućni', '+385 24 101 773');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Poslovni mobitel', '+385 99 396 4329');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Instagram', 'www.instagram.com/relaxunlisted');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Mobitel', '+385 95 458 8558');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Fax', '+385 60 253 346');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Na poslu', '+385 30 862 160');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Privatna e-mail adresa', 'oceanyangon@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (38, 'Skype', 'pleetquantum84');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Skype', 'kidneysmoncton64');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Instagram', 'www.instagram.com/refplayer');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Privatna e-mail adresa', 'pleetquantum@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Na poslu', '+385 46 450 839');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Poslovna e-mail adresa', 'yardbradford@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Mobitel', '+385 95 817 9102');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Poslovni mobitel', '+385 97 392 6516');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Fax', '+385 57 364 294');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (39, 'Kućni', '+385 48 477 328');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (40, 'Facebook', 'www.facebook.com/landminefencing');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (40, 'Na poslu', '+385 38 516 449');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (40, 'Poslovni mobitel', '+385 95 575 7624');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (40, 'Poslovna e-mail adresa', 'spitegrooming@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (40, 'Instagram', 'www.instagram.com/scarcecraggs');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (40, 'Kućni', '+385 71 728 341');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Facebook', 'www.facebook.com/wakefieldaground');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Kućni', '+385 44 269 442');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Poslovni mobitel', '+385 95 140 7324');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Fax', '+385 77 813 281');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Poslovna e-mail adresa', 'pepcry@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Na poslu', '+385 45 981 675');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Mobitel', '+385 95 649 7227');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Skype', 'jokinglylanyard69');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (41, 'Instagram', 'www.instagram.com/hurrywanting');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Poslovna e-mail adresa', 'scuppergantry@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Instagram', 'www.instagram.com/aerosolcornea');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Skype', 'favornecked35');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Mobitel', '+385 97 998 3216');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Poslovni mobitel', '+385 92 634 8372');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Na poslu', '+385 25 139 660');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Privatna e-mail adresa', 'ponymolecular@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Fax', '+385 86 749 205');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (42, 'Kućni', '+385 61 219 542');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (43, 'Privatna e-mail adresa', 'quaintcheck@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (43, 'Skype', 'scuffrod68');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (43, 'Na poslu', '+385 81 249 261');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (44, 'Skype', 'pellytox62');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (44, 'Instagram', 'www.instagram.com/unificationore');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (44, 'Facebook', 'www.facebook.com/cosinesstraggler');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (44, 'Na poslu', '+385 73 824 103');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (44, 'Poslovni mobitel', '+385 98 871 1647');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (44, 'Privatna e-mail adresa', 'nostalgictairy@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (46, 'Kućni', '+385 99 969 546');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Poslovna e-mail adresa', 'dialectundesired@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Facebook', 'www.facebook.com/fitterdigging');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Mobitel', '+385 98 242 5701');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Instagram', 'www.instagram.com/startingmanila');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Poslovni mobitel', '+385 91 285 3287');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Privatna e-mail adresa', 'wongamud@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Na poslu', '+385 79 894 405');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (48, 'Kućni', '+385 21 755 750');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Poslovni mobitel', '+385 91 309 6311');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Poslovna e-mail adresa', 'nostalgictairy@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Na poslu', '+385 39 355 236');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Mobitel', '+385 99 976 2104');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Skype', 'frankchad39');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Facebook', 'www.facebook.com/anxietymogul');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Privatna e-mail adresa', 'currencypartridge@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (49, 'Kućni', '+385 71 698 668');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Privatna e-mail adresa', 'frazzlediconic@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Poslovna e-mail adresa', 'hotelwheat@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Poslovni mobitel', '+385 97 460 5083');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Fax', '+385 29 586 235');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Kućni', '+385 27 466 608');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Mobitel', '+385 98 261 1634');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Na poslu', '+385 83 589 330');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Skype', 'pauperrevolt33');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (50, 'Facebook', 'www.facebook.com/tuffhonoria');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (51, 'Facebook', 'www.facebook.com/slippedskulk');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (51, 'Poslovni mobitel', '+385 99 634 6869');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (52, 'Poslovna e-mail adresa', 'exactingbrushes@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (52, 'Facebook', 'www.facebook.com/scuppergantry');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (52, 'Mobitel', '+385 95 618 8844');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (52, 'Instagram', 'www.instagram.com/lizlevel');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (52, 'Na poslu', '+385 12 991 100');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (52, 'Kućni', '+385 44 671 786');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (53, 'Instagram', 'www.instagram.com/wakefieldaground');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (53, 'Poslovni mobitel', '+385 97 193 2272');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (53, 'Kućni', '+385 35 266 876');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (53, 'Na poslu', '+385 67 990 210');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (53, 'Skype', 'mobilizekirkaig55');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Kućni', '+385 90 229 877');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Instagram', 'www.instagram.com/fearfulkepler');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Fax', '+385 25 838 360');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Na poslu', '+385 30 676 643');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Skype', 'severityspectacle48');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Privatna e-mail adresa', 'raftingdiaphragm@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Facebook', 'www.facebook.com/morainefetch');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Poslovna e-mail adresa', 'steepsammy@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (54, 'Mobitel', '+385 91 718 3185');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (55, 'Facebook', 'www.facebook.com/startingmanila');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (55, 'Fax', '+385 18 391 877');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Privatna e-mail adresa', 'slippedskulk@gmail.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Facebook', 'www.facebook.com/raftingdiaphragm');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Instagram', 'www.instagram.com/magneticfrancium');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Poslovna e-mail adresa', 'obviouschurch@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Mobitel', '+385 98 623 5906');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Na poslu', '+385 26 109 175');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Fax', '+385 41 687 800');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (57, 'Poslovni mobitel', '+385 95 132 3022');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (58, 'Fax', '+385 80 131 834');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (58, 'Poslovna e-mail adresa', 'gentlemanyorkshire@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (58, 'Instagram', 'www.instagram.com/slippedskulk');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (58, 'Kućni', '+385 94 940 790');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Instagram', 'www.instagram.com/foolaqua');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Mobitel', '+385 99 100 7499');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Poslovna e-mail adresa', 'gaurscandale@live.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Kućni', '+385 51 448 568');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Fax', '+385 13 948 248');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Na poslu', '+385 80 191 185');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Poslovni mobitel', '+385 92 179 3616');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (59, 'Skype', 'hawkcrooked10');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (60, 'Privatna e-mail adresa', 'annoyarrest@outlook.com');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (60, 'Poslovni mobitel', '+385 92 729 1366');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (60, 'Instagram', 'www.instagram.com/schedulestruthful');
INSERT INTO kontakt (osoba_osb_id, vrsta, vrijednost) VALUES (60, 'Na poslu', '+385 79 415 586');