INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (1, 'PINSCHER', 'PINČERI', 'PINČERI', 1, 3);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (2, 'SCHNAUZER', 'ŠNAUCERI', 'ŠNAUCERI', 2, 3);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (3, 'SMOUSHOND', 'HOLANDSKI PINČ', 'NIZOZEMSKI PINČ', 3, 3);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (4, 'TCHIORNY TERRIER', 'CRNI TERIJER', 'CRNI TERIJER', 4, 3);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (1, 'MASTIFF TYPE', 'TIP MASTIF', 'TIP MASTIF', 5, 4);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (2, 'MOUNTAIN TYPE', 'PLANINSKI TIP', 'PLANINSKI TIP', 6, 4);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (1, 'LARGE-SIZED HOUNDS', 'VELIKI GONIČI', 'VELIKI GONIČI', 7, 17);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (2, 'MEDIUM-SIZED HOUNDS', 'GONIČI SREDNJEG RASTA', 'GONIČI SREDNJEG RASTA', 8, 17);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (3, 'SMALL-SIZED HOUNDS', 'GONIČI MALOG RASTA', 'GONIČI MALOG RASTA', 9, 17);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (1, '«BRAQUE»TYPE', 'TIP BRAKO', 'TIP BRAKO', 10, 20);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (2, 'SPANIEL TYPE', 'TIP ŠPANIJEL', 'TIP ŠPANIJEL', 11, 20);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (3, '«GRIFFON» TYPE', 'TIP GRIFON', 'TIP GRIFON', 12, 20);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (1, 'POINTER', 'POINTERI', 'POINTERI', 13, 21);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (2, 'SETTER', 'SETERI', 'SETTERI', 14, 21);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (1, 'BICHONS', 'BISHONI', 'BISHONI', 15, 25);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (2, 'COTON DE TULÉAR', 'COTON DE TULÉAR', 'COTON DE TULÉAR', 16, 25);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (3, 'PETIT CHIEN LION', 'PETIT CHIEN LION', 'PETIT CHIEN LION', 17, 25);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (1, 'GRIFFONS', 'GRIFONI', 'GRIFONI', 18, 27);

INSERT INTO FCI_PSEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCP_ID, FCI_SEK_FCS_ID) 
VALUES (2, 'PETIT BRABANÇON', 'MALI BARBANSON', 'MALI BARBANSON', 19, 27);