INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Adrian', 'Medved', NULL, 'Klijent', 'M', TO_DATE('1968-02-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nika', 'Špoljarić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Una', 'Mijatović', 'Matijašević', 'Klijent', 'Z', TO_DATE('1997-02-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Luka', 'Radić', NULL, 'Klijent', 'M', TO_DATE('1991-10-27', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikol', 'Šimunović', NULL, 'Klijent', 'Z', TO_DATE('1972-10-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Klara', 'Burić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabrijel', 'Bačić', NULL, 'Djelatnik', 'M', TO_DATE('1986-03-09', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noel', 'Matanović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petra', 'Petković', NULL, 'Klijent', 'Z', TO_DATE('1985-05-18', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriela', 'Grgurić', 'Benčić', 'Klijent', 'Z', TO_DATE('1956-04-17', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dora', 'Tomašević', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Štimac', 'Glavaš', 'Klijent', 'Z', TO_DATE('1963-07-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovre', 'Pejić', NULL, 'Klijent', 'M', TO_DATE('1940-11-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dominik', 'Grgurić', NULL, 'Klijent', 'M', TO_DATE('1943-10-17', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Roko', 'Milošević', NULL, 'Klijent', 'M', TO_DATE('1944-11-01', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabrijel', 'Živković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Klara', 'Cvitković', NULL, 'Klijent', 'Z', TO_DATE('1966-03-09', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruna', 'Jurčić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lana', 'Crnković', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dominik', 'Majstorović', NULL, 'Klijent', 'M', TO_DATE('1987-11-21', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dora', 'Ilić', NULL, 'Klijent', 'Z', TO_DATE('1955-03-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Roko', 'Jurčević', NULL, 'Klijent', 'M', TO_DATE('1999-08-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Erik', 'Posavec', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Đukić', 'Turkalj', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriela', 'Tomašić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tin', 'Vučković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lana', 'Vrdoljak', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Maša', 'Majstorović', 'Novaković', 'Klijent', 'Z', TO_DATE('1988-04-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mihael', 'Budimir', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marta', 'Štimac', NULL, 'Klijent', 'Z', TO_DATE('1943-12-20', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Patrik', 'Matić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Teo', 'Petković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katarina', 'Petrović', NULL, 'Klijent', 'Z', TO_DATE('1999-04-20', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nora', 'Turkalj', NULL, 'Klijent', 'Z', TO_DATE('1994-02-18', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mila', 'Bošković', 'Novak', 'Klijent', 'Z', TO_DATE('1958-12-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Maša', 'Sever', 'Turković', 'Klijent', 'Z', TO_DATE('1989-07-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marija', 'Bašić', NULL, 'Klijent', 'Z', TO_DATE('1976-01-25', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Karlo', 'Mitrović', NULL, 'Klijent', 'M', TO_DATE('1944-10-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Patrik', 'Blažević', NULL, 'Klijent', 'M', TO_DATE('1955-08-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tia', 'Benković', 'Knežević', 'Klijent', 'Z', TO_DATE('1972-04-20', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jakov', 'Brčić', NULL, 'Klijent', 'M', TO_DATE('1966-09-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tena', 'Kovačević', 'Tadić', 'Klijent', 'Z', TO_DATE('1955-02-13', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ema', 'Bačić', 'Milošević', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noa', 'Krizmanić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tea', 'Novosel', 'Mišković', 'Klijent', 'Z', TO_DATE('1986-02-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mila', 'Kurtović', 'Dukić', 'Djelatnik', 'Z', TO_DATE('1945-07-21', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabrijel', 'Ivanović', NULL, 'Djelatnik', 'M', TO_DATE('1991-10-25', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Erik', 'Radić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Franka', 'Rendulić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marta', 'Lukić', NULL, 'Klijent', 'Z', TO_DATE('1948-11-12', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lorena', 'Šimić', 'Bašić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vita', 'Kujundžić', NULL, 'Klijent', 'Z', TO_DATE('1998-02-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lara', 'Novak', 'Dragičević', 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Helena', 'Barbarić', NULL, 'Klijent', 'Z', TO_DATE('1966-06-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mia', 'Mikulić', 'Matošević', 'Klijent', 'Z', TO_DATE('1988-09-23', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tin', 'Kovač', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noa', 'Ljubić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Antonio', 'Vrdoljak', NULL, 'Klijent', 'M', TO_DATE('1967-02-01', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Andrej', 'Grubišić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Adrian', 'Vlašić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petra', 'Marković', NULL, 'Klijent', 'Z', TO_DATE('1954-01-31', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jakov', 'Dukić', NULL, 'Klijent', 'M', TO_DATE('1951-03-03', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Laura', 'Živković', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriela', 'Kos', NULL, 'Klijent', 'Z', TO_DATE('1998-08-22', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Teo', 'Karlović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Antonio', 'Kralj', NULL, 'Klijent', 'M', TO_DATE('1994-12-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruno', 'Kos', NULL, 'Klijent', 'M', TO_DATE('1996-02-21', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikol', 'Franjić', 'Valentić', 'Djelatnik', 'Z', TO_DATE('1987-03-03', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Duje', 'Josipović', NULL, 'Klijent', 'M', TO_DATE('1940-02-22', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noel', 'Pavković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Matija', 'Kordić', NULL, 'Djelatnik', 'M', TO_DATE('1953-11-04', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Iva', 'Budimir', NULL, 'Klijent', 'Z', TO_DATE('1985-03-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sofia', 'Klarić', 'Klarić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Adrian', 'Balić', NULL, 'Klijent', 'M', TO_DATE('1978-11-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tea', 'Damjanović', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dora', 'Mikulić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Matija', 'Bogović', NULL, 'Klijent', 'M', TO_DATE('2000-03-25', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Iva', 'Abramović', 'Galić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leona', 'Pavić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Fran', 'Jerković', NULL, 'Klijent', 'M', TO_DATE('1955-01-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Erik', 'Novak', NULL, 'Klijent', 'M', TO_DATE('1953-09-25', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikol', 'Medved', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tena', 'Matić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lena', 'Grubišić', NULL, 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Iva', 'Delić', NULL, 'Klijent', 'Z', TO_DATE('1940-05-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Maša', 'Poljak', NULL, 'Klijent', 'Z', TO_DATE('1950-10-06', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Brkić', NULL, 'Klijent', 'M', TO_DATE('1940-01-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tin', 'Mlinarić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tea', 'Dragičević', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lea', 'Stanković', 'Jovanović', 'Klijent', 'Z', TO_DATE('1990-11-12', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriel', 'Bogdan', NULL, 'Klijent', 'M', TO_DATE('1978-02-12', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toni', 'Janković', NULL, 'Klijent', 'M', TO_DATE('1997-10-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noel', 'Andrić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marin', 'Varga', NULL, 'Klijent', 'M', TO_DATE('1976-06-04', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mia', 'Petković', 'Šimunović', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovre', 'Majstorović', NULL, 'Djelatnik', 'M', TO_DATE('1972-02-18', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Filip', 'Benčić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Jerković', NULL, 'Klijent', 'M', TO_DATE('1977-05-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leon', 'Brčić', NULL, 'Klijent', 'M', TO_DATE('1972-10-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Karla', 'Kolarić', 'Babić', 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marta', 'Ilić', NULL, 'Klijent', 'Z', TO_DATE('1949-12-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nora', 'Sabljak', 'Bošković', 'Klijent', 'Z', TO_DATE('1956-07-12', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikol', 'Pavičić', 'Golub', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lukas', 'Cvitković', NULL, 'Klijent', 'M', TO_DATE('1989-07-12', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leona', 'Lučić', 'Marić', 'Klijent', 'Z', TO_DATE('1941-11-03', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Erik', 'Šimunić', NULL, 'Djelatnik', 'M', TO_DATE('1979-06-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Franka', 'Martinović', 'Bilić', 'Djelatnik', 'Z', TO_DATE('1994-10-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dora', 'Golubić', 'Marković', 'Klijent', 'Z', TO_DATE('1959-12-21', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katarina', 'Zorić', 'Kralj', 'Klijent', 'Z', TO_DATE('1986-06-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Helena', 'Petrović', 'Cvitković', 'Klijent', 'Z', TO_DATE('1981-09-03', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toni', 'Dragičević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dominik', 'Matošević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Bačić', 'Lončarić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lukas', 'Vlahović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Starčević', NULL, 'Djelatnik', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jan', 'Mustapić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Viktor', 'Dujmović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Franka', 'Šimić', 'Jelić', 'Djelatnik', 'Z', TO_DATE('1956-06-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tara', 'Grgurić', 'Pavić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toma', 'Glavaš', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovre', 'Ilić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Paula', 'Jakšić', NULL, 'Djelatnik', 'Z', TO_DATE('1947-12-24', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Luka', 'Dragičević', NULL, 'Djelatnik', 'M', TO_DATE('1982-12-22', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikol', 'Benković', NULL, 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Paula', 'Lončar', NULL, 'Klijent', 'Z', TO_DATE('1975-08-09', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lana', 'Meštrović', NULL, 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ana', 'Devčić', 'Blažević', 'Klijent', 'Z', TO_DATE('1994-02-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tia', 'Grubišić', NULL, 'Klijent', 'Z', TO_DATE('1968-12-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lara', 'Balić', 'Marjanović', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ana', 'Tomašić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lorena', 'Golubić', NULL, 'Klijent', 'Z', TO_DATE('1969-08-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lukas', 'Bogdanović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sara', 'Šarić', 'Pintarić', 'Klijent', 'Z', TO_DATE('1966-08-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mia', 'Antolović', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Erik', 'Pavić', NULL, 'Klijent', 'M', TO_DATE('1990-02-23', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikola', 'Vidaković', NULL, 'Klijent', 'M', TO_DATE('1981-11-19', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tena', 'Matić', NULL, 'Klijent', 'Z', TO_DATE('1960-02-18', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nika', 'Matković', NULL, 'Djelatnik', 'Z', TO_DATE('1974-09-24', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Karlo', 'Jakšić', NULL, 'Klijent', 'M', TO_DATE('1971-01-06', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petra', 'Dragičević', NULL, 'Djelatnik', 'Z', TO_DATE('1989-04-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikola', 'Mandić', NULL, 'Klijent', 'M', TO_DATE('1949-09-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noel', 'Petrović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tia', 'Pavičić', 'Sekulić', 'Djelatnik', 'Z', TO_DATE('1992-06-04', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tara', 'Varga', 'Knežević', 'Klijent', 'Z', TO_DATE('1994-11-21', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Roko', 'Franjić', NULL, 'Klijent', 'M', TO_DATE('1943-07-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Eva', 'Damjanović', NULL, 'Klijent', 'Z', TO_DATE('1985-07-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Elena', 'Matić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Viktor', 'Kos', NULL, 'Djelatnik', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toma', 'Valentić', NULL, 'Klijent', 'M', TO_DATE('1992-01-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nina', 'Marjanović', 'Golub', 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Klara', 'Galić', NULL, 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mila', 'Kos', NULL, 'Klijent', 'Z', TO_DATE('1966-04-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Roko', 'Bošković', NULL, 'Klijent', 'M', TO_DATE('1997-06-21', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Erik', 'Petković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mihael', 'Mikulić', NULL, 'Klijent', 'M', TO_DATE('1969-05-27', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Paula', 'Jozić', NULL, 'Klijent', 'Z', TO_DATE('1983-09-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sara', 'Ružić', 'Martinović', 'Klijent', 'Z', TO_DATE('1997-07-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sofia', 'Sabljak', 'Đurić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toma', 'Jurković', NULL, 'Klijent', 'M', TO_DATE('1942-09-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petar', 'Matić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Una', 'Mišković', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sofia', 'Pejić', NULL, 'Klijent', 'Z', TO_DATE('1982-04-27', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikola', 'Brajković', NULL, 'Djelatnik', 'M', TO_DATE('1992-02-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovro', 'Matijašević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikola', 'Samardžić', NULL, 'Klijent', 'M', TO_DATE('1947-10-24', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Franka', 'Vlahović', 'Kraljević', 'Klijent', 'Z', TO_DATE('1956-11-20', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petar', 'Pavić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Teo', 'Bogović', NULL, 'Klijent', 'M', TO_DATE('1989-04-20', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Karlo', 'Jurčević', NULL, 'Klijent', 'M', TO_DATE('1941-04-17', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Eva', 'Vučković', 'Meštrović', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Antonio', 'Jovanović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ella', 'Bošković', 'Sertić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Niko', 'Tomić', NULL, 'Klijent', 'M', TO_DATE('1949-07-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Klara', 'Perković', 'Jurišić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Mijatović', NULL, 'Klijent', 'Z', TO_DATE('1950-01-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mila', 'Miletić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leona', 'Grgurić', NULL, 'Klijent', 'Z', TO_DATE('1946-10-31', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mateo', 'Pavić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lena', 'Pejić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petra', 'Meštrović', 'Majstorović', 'Klijent', 'Z', TO_DATE('1954-06-22', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Babić', NULL, 'Klijent', 'M', TO_DATE('1981-06-06', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Roko', 'Vuković', NULL, 'Klijent', 'M', TO_DATE('1989-11-27', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vita', 'Jurčević', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ivano', 'Bačić', NULL, 'Klijent', 'M', TO_DATE('1994-05-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Adrian', 'Kolar', NULL, 'Klijent', 'M', TO_DATE('1955-04-22', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tin', 'Mihaljević', NULL, 'Klijent', 'M', TO_DATE('1991-08-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Teo', 'Savić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('David', 'Dukić', NULL, 'Klijent', 'M', TO_DATE('1993-08-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marija', 'Novosel', NULL, 'Klijent', 'Z', TO_DATE('1947-02-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mateo', 'Martinović', NULL, 'Klijent', 'M', TO_DATE('1959-06-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vita', 'Marinović', 'Tomašević', 'Klijent', 'Z', TO_DATE('1948-04-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dora', 'Lončarić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mila', 'Cindrić', NULL, 'Klijent', 'Z', TO_DATE('1977-01-18', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tea', 'Posavec', 'Jakšić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lukas', 'Marjanović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nina', 'Jozić', NULL, 'Klijent', 'Z', TO_DATE('1971-01-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabrijel', 'Božić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ante', 'Blažević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mihael', 'Kurtović', NULL, 'Klijent', 'M', TO_DATE('1972-01-01', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Grgić', 'Jurić', 'Klijent', 'Z', TO_DATE('1959-10-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Elena', 'Ostojić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('David', 'Vlašić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovro', 'Vlašić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Krznarić', NULL, 'Klijent', 'M', TO_DATE('1947-05-27', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vito', 'Bošnjak', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikol', 'Đurić', 'Novosel', 'Klijent', 'Z', TO_DATE('1972-06-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Erik', 'Crnković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Karla', 'Lukić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Borna', 'Jukić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leona', 'Stanković', 'Rendulić', 'Klijent', 'Z', TO_DATE('1988-01-24', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('David', 'Ilić', NULL, 'Klijent', 'M', TO_DATE('1947-03-05', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tara', 'Janković', NULL, 'Klijent', 'Z', TO_DATE('1985-06-24', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noa', 'Bošnjak', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petar', 'Petrić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Luka', 'Vlašić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sara', 'Šimunović', 'Matošević', 'Klijent', 'Z', TO_DATE('1974-11-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jana', 'Bogdanović', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vito', 'Krznarić', NULL, 'Klijent', 'M', TO_DATE('1957-10-25', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tara', 'Abramović', 'Bošnjak', 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Matea', 'Bilić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Cvitković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Iva', 'Medved', 'Vojnović', 'Klijent', 'Z', TO_DATE('1948-06-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mihael', 'Horvat', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ante', 'Burić', NULL, 'Klijent', 'M', TO_DATE('1976-09-23', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabrijel', 'Blažević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tea', 'Kos', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Patrik', 'Lončarić', NULL, 'Klijent', 'M', TO_DATE('1981-05-25', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mila', 'Meštrović', NULL, 'Klijent', 'Z', TO_DATE('1951-11-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sara', 'Kralj', 'Pavelić', 'Klijent', 'Z', TO_DATE('1987-09-19', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Matej', 'Kovačević', NULL, 'Klijent', 'M', TO_DATE('2001-06-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nora', 'Sertić', 'Brčić', 'Klijent', 'Z', TO_DATE('1974-01-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriel', 'Barić', NULL, 'Klijent', 'M', TO_DATE('1975-03-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Novaković', NULL, 'Klijent', 'M', TO_DATE('1956-05-24', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Matej', 'Mišković', NULL, 'Klijent', 'M', TO_DATE('1948-08-14', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Fran', 'Pavić', NULL, 'Klijent', 'M', TO_DATE('1957-08-06', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabrijel', 'Rendulić', NULL, 'Djelatnik', 'M', TO_DATE('1994-08-01', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriela', 'Milošević', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Rita', 'Marinović', 'Ostojić', 'Klijent', 'Z', TO_DATE('1949-02-06', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ella', 'Jozić', 'Šimić', 'Klijent', 'Z', TO_DATE('1974-08-21', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sofia', 'Kolar', 'Pavić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mateo', 'Matijević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Matić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marin', 'Lučić', NULL, 'Klijent', 'M', TO_DATE('1998-05-26', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jana', 'Damjanović', 'Kovačić', 'Klijent', 'Z', TO_DATE('1992-11-01', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikola', 'Novak', NULL, 'Djelatnik', 'M', TO_DATE('1997-08-31', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Martin', 'Sever', NULL, 'Klijent', 'M', TO_DATE('1973-07-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nika', 'Sertić', 'Krizmanić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Luka', 'Devčić', NULL, 'Klijent', 'M', TO_DATE('1963-11-23', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Pavković', NULL, 'Klijent', 'Z', TO_DATE('1946-06-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Laura', 'Vidaković', NULL, 'Klijent', 'Z', TO_DATE('1951-09-13', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tara', 'Šimunović', 'Kovačević', 'Klijent', 'Z', TO_DATE('1951-03-31', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('David', 'Zorić', NULL, 'Djelatnik', 'M', TO_DATE('1961-08-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriel', 'Jerković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovro', 'Nikolić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nora', 'Marić', 'Butković', 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Patrik', 'Perković', NULL, 'Klijent', 'M', TO_DATE('1964-05-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lucija', 'Kos', 'Mustapić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tin', 'Kovačić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jan', 'Radić', NULL, 'Klijent', 'M', TO_DATE('1994-09-19', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovro', 'Knežević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leona', 'Jozić', NULL, 'Klijent', 'Z', TO_DATE('1991-10-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruno', 'Sertić', NULL, 'Klijent', 'M', TO_DATE('1966-04-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ema', 'Knezović', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Viktor', 'Horvatić', NULL, 'Klijent', 'M', TO_DATE('1970-01-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leona', 'Radić', NULL, 'Klijent', 'Z', TO_DATE('1995-08-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toni', 'Stipić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Rita', 'Šarić', 'Marić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sofia', 'Stanković', 'Bogdanović', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Viktor', 'Grubišić', NULL, 'Djelatnik', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Duje', 'Bošković', NULL, 'Djelatnik', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Franka', 'Vojnović', 'Galić', 'Klijent', 'Z', TO_DATE('1960-01-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Lukić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ivan', 'Mišković', NULL, 'Klijent', 'M', TO_DATE('1958-04-03', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jan', 'Jurčević', NULL, 'Djelatnik', 'M', TO_DATE('1988-03-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jana', 'Antolović', NULL, 'Klijent', 'Z', TO_DATE('1965-01-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mia', 'Novosel', 'Medved', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nina', 'Jurčević', 'Lončar', 'Djelatnik', 'Z', TO_DATE('1968-03-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Klara', 'Karlović', NULL, 'Klijent', 'Z', TO_DATE('1959-03-31', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Karlo', 'Kovačić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lukas', 'Bartulović', NULL, 'Djelatnik', 'M', TO_DATE('1977-09-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leona', 'Novak', NULL, 'Klijent', 'Z', TO_DATE('1987-02-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Martin', 'Radošević', NULL, 'Klijent', 'M', TO_DATE('1988-03-03', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Adrian', 'Mlinarić', NULL, 'Klijent', 'M', TO_DATE('1986-11-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lorena', 'Krizmanić', 'Antolović', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tia', 'Barišić', NULL, 'Klijent', 'Z', TO_DATE('1990-08-12', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Borna', 'Dragičević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Radošević', NULL, 'Klijent', 'Z', TO_DATE('1995-01-17', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('David', 'Mijatović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Magdalena', 'Knezović', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tea', 'Rendulić', 'Karlović', 'Klijent', 'Z', TO_DATE('1996-11-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruno', 'Katić', NULL, 'Klijent', 'M', TO_DATE('1975-01-13', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mihael', 'Nikolić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lorena', 'Josipović', 'Vlahović', 'Klijent', 'Z', TO_DATE('1962-08-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Martin', 'Barić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Maša', 'Jurišić', 'Lučić', 'Klijent', 'Z', TO_DATE('1975-04-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Josip', 'Petrović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tena', 'Ćosić', 'Špoljarić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lena', 'Babić', NULL, 'Klijent', 'Z', TO_DATE('1965-12-04', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruna', 'Jovanović', NULL, 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jan', 'Grubišić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dino', 'Benković', NULL, 'Klijent', 'M', TO_DATE('1954-07-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ema', 'Stanković', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mila', 'Ivković', 'Mišković', 'Klijent', 'Z', TO_DATE('1969-08-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vito', 'Mustapić', NULL, 'Klijent', 'M', TO_DATE('1985-03-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ella', 'Vojnović', 'Andrić', 'Klijent', 'Z', TO_DATE('1991-08-11', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruno', 'Đurđević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Duje', 'Savić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Budimir', 'Jakovljević', 'Klijent', 'Z', TO_DATE('2000-12-14', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ema', 'Antolović', NULL, 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tea', 'Božić', NULL, 'Klijent', 'Z', TO_DATE('1953-07-18', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Janković', NULL, 'Klijent', 'Z', TO_DATE('1969-07-05', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabrijel', 'Špoljarić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Duje', 'Savić', NULL, 'Klijent', 'M', TO_DATE('1948-01-13', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruno', 'Krizmanić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Martin', 'Pavelić', NULL, 'Klijent', 'M', TO_DATE('1956-09-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dominik', 'Jurčić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Delić', 'Marušić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Niko', 'Petrović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Eva', 'Lučić', 'Karlović', 'Klijent', 'Z', TO_DATE('1951-06-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tena', 'Jurčić', 'Posavec', 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Duvnjak', 'Matijašević', 'Klijent', 'Z', TO_DATE('1992-05-20', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nikola', 'Dragičević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ena', 'Vukelić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Andrej', 'Duvnjak', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Niko', 'Marinović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Hana', 'Sertić', 'Benković', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jana', 'Duvnjak', NULL, 'Klijent', 'Z', TO_DATE('1960-03-01', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ante', 'Bogović', NULL, 'Klijent', 'M', TO_DATE('1971-05-09', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruna', 'Matošević', NULL, 'Klijent', 'Z', TO_DATE('1940-05-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marija', 'Horvat', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katarina', 'Gudelj', NULL, 'Klijent', 'Z', TO_DATE('1966-12-28', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Sofia', 'Horvat', NULL, 'Klijent', 'Z', TO_DATE('1969-03-05', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Adrian', 'Bačić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petar', 'Turkalj', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Niko', 'Mandić', NULL, 'Klijent', 'M', TO_DATE('2000-05-12', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Helena', 'Štimac', 'Lučić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Marko', 'Ivančić', NULL, 'Djelatnik', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jana', 'Posavec', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Teo', 'Grgurić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nora', 'Jovanović', 'Mustapić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Hana', 'Brajković', 'Jukić', 'Klijent', 'Z', TO_DATE('1978-01-01', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Fran', 'Mustapić', NULL, 'Klijent', 'M', TO_DATE('1961-10-24', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vita', 'Stanković', 'Kurtović', 'Djelatnik', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jan', 'Đukić', NULL, 'Djelatnik', 'M', TO_DATE('1971-03-30', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ema', 'Jurjević', 'Martić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Niko', 'Matijević', NULL, 'Klijent', 'M', TO_DATE('1963-07-14', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Magdalena', 'Klarić', 'Rendulić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leo', 'Matošević', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noel', 'Knezović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruno', 'Matanović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dominik', 'Jakšić', NULL, 'Klijent', 'M', TO_DATE('1954-09-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Doris', 'Radošević', NULL, 'Klijent', 'Z', TO_DATE('1998-02-15', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petar', 'Glavaš', NULL, 'Djelatnik', 'M', TO_DATE('1941-04-08', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Iva', 'Krznarić', NULL, 'Klijent', 'Z', TO_DATE('1999-02-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lara', 'Ivančić', 'Kos', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Elena', 'Pavković', 'Đurđević', 'Klijent', 'Z', TO_DATE('1952-03-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Jana', 'Petričević', 'Mikulić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tia', 'Mijatović', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Laura', 'Nikolić', 'Budimir', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Maša', 'Brkić', NULL, 'Klijent', 'Z', TO_DATE('1978-04-17', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Matej', 'Cvitković', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toma', 'Cvetković', NULL, 'Klijent', 'M', TO_DATE('1951-10-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Dino', 'Babić', NULL, 'Djelatnik', 'M', TO_DATE('1942-02-23', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Iva', 'Pavičić', 'Marković', 'Klijent', 'Z', TO_DATE('1971-07-31', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toma', 'Radočaj', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Franka', 'Bošković', 'Antolović', 'Klijent', 'Z', TO_DATE('1995-07-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Mia', 'Ivančić', 'Lončarić', 'Djelatnik', 'Z', TO_DATE('1940-09-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vito', 'Bačić', NULL, 'Djelatnik', 'M', TO_DATE('1950-11-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Rafael', 'Matanović', NULL, 'Klijent', 'M', TO_DATE('1952-10-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Ljubić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Šimun', 'Delić', NULL, 'Djelatnik', 'M', TO_DATE('1954-08-18', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nika', 'Matijašević', 'Filipović', 'Klijent', 'Z', TO_DATE('1965-07-13', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Paula', 'Vidaković', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noel', 'Antunović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Eva', 'Stipić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Matea', 'Knežević', 'Popović', 'Klijent', 'Z', TO_DATE('1994-06-13', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Gabriela', 'Kozina', 'Krznarić', 'Klijent', 'Z', TO_DATE('1995-08-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lana', 'Marković', NULL, 'Klijent', 'Z', TO_DATE('1941-10-03', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Leo', 'Knezović', NULL, 'Djelatnik', 'M', TO_DATE('1951-08-25', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nika', 'Rajković', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Karlo', 'Josipović', NULL, 'Klijent', 'M', TO_DATE('1943-06-16', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Petar', 'Antolović', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Ela', 'Stanić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Šimun', 'Jurjević', NULL, 'Djelatnik', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Klara', 'Valentić', NULL, 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Nora', 'Matošević', 'Erceg', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Iva', 'Pavlić', 'Josipović', 'Klijent', 'Z', TO_DATE('1992-07-07', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Toma', 'Babić', NULL, 'Klijent', 'M', TO_DATE('1984-11-02', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Fran', 'Barić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Hana', 'Erceg', 'Balić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Tena', 'Janković', 'Mihaljević', 'Klijent', 'Z', TO_DATE('2000-04-10', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lara', 'Kovačević', 'Puškarić', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lovre', 'Perić', NULL, 'Klijent', 'M', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Lucija', 'Tomašić', 'Matijević', 'Klijent', 'Z', TO_DATE('1980-11-14', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruna', 'Pintarić', 'Jukić', 'Klijent', 'Z', TO_DATE('1981-08-09', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Katja', 'Ivančić', 'Sever', 'Klijent', 'Z', NULL);
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Bruno', 'Pavić', NULL, 'Klijent', 'M', TO_DATE('1982-08-17', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Rafael', 'Vuković', NULL, 'Klijent', 'M', TO_DATE('1991-10-31', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Noel', 'Grgić', NULL, 'Djelatnik', 'M', TO_DATE('1995-10-29', 'YYYY-MM-DD'));
INSERT INTO osoba (ime, prezime, drugo_prezime, uloga, spol, datum_rodjenja) VALUES ('Vito', 'Cindrić', NULL, 'Klijent', 'M', TO_DATE('1967-09-07', 'YYYY-MM-DD'));

