INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (1, 'SHEEPDOGS AND CATTLEDOGS (EXCEPT SWISS CATTLEDOGS)', 'PASTIRSKI PSI I PSI TERAČI STOKE (SEM ŠVAJCARSKI PASTIRSKIH PASA)', 'PASTIRSKI PSI I PSI TJERAČI GOVEDA (OSIM ŠVICARSKIH PASTIRSKIH PASA)', 1);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (2, 'PINSCHER AND SCHNAUZER - MOLOSSOID AND SWISS MOUNTAIN AND CATTLEDOGS', 'PINČERI I ŠNAUCERI, MOLOSI I ŠVAJCARSKI PASTIRSKI PSI', 'PINČEVI I ŠNAUCERI, MOLOSII, ŠVICARSKI PASTIRSKI PAS', 2);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (3, 'TERRIERS', 'TERIJERI', 'TERIJERI', 3);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (4, 'DACHSHUNDS', 'JAZAVIČARI', 'JAZAVČARI', 4);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (5, 'SPITZ AND PRIMITIVE TYPES', 'ŠPIC TIP I PRIMITIVNI TIP PASA', 'ŠPICTIP I PRIMITIVNI TIP PASA', 5);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (6, 'SCENT HOUNDS AND RELATED BREEDS', 'GONIČI,TRAGAČI PO KRVI I SRODNE RASE', 'GONIČI, TRAGAČI PO KRVI I SRODNE PASMINE', 6);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (7, 'POINTING DOGS', 'PTIČARI', 'PTIČARI', 7);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (8, 'RETRIEVERS - FLUSHING DOGS - WATER DOGS', 'RETRIVERI, CUNJAVCI I PSI ZA VODU', 'RETRIVERI, ŠPANIJELI I PSI ZA VODU', 8);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (9, 'COMPANION AND TOY DOGS', 'PSI ZA PRATNJU I RAZONODU', 'PSI ZA PRATNJU I RAZONODU', 9);

INSERT INTO FCI_GR (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCG_ID) 
VALUES (10, 'SIGHTHOUNDS', 'HRTOVI', 'HRTOVI', 10);
