INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 683.62, 1 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 1 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 27.24, 2 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 2 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 400.81, 3 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-07-09', 'YYYY-MM-DD'), 1, 3 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-07-09', 'YYYY-MM-DD'), TO_DATE('2019-12-05', 'YYYY-MM-DD'), 3, 3 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2020-04-24', 'YYYY-MM-DD'), NULL, 4, 3 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 903.38, 4 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 4 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 942.04, 5 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 5 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 697.04, 6 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 6 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 402.22, 7 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 7 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 217.09, 8 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 9, 8 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 563.92, 9 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-09-28', 'YYYY-MM-DD'), 6, 9 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-07-05', 'YYYY-MM-DD'), TO_DATE('2019-07-29', 'YYYY-MM-DD'), 2, 9 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-08-09', 'YYYY-MM-DD'), NULL, 2, 9 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 506.65, 10 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 10 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 203.37, 11 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 11 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 824.65, 12 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 12 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 699.25, 13 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 13 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 520.42, 14 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 8, 14 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 713.71, 15 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 15 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 914.45, 16 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 16 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 276.9, 17 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 17 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2019-09-24', 'YYYY-MM-DD'), 601.77, 18 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2019-09-25', 'YYYY-MM-DD'), TO_DATE('2019-10-06', 'YYYY-MM-DD'), 129.86, 18 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2019-10-07', 'YYYY-MM-DD'), NULL, 599.34, 18 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 18 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 860.01, 19 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 19 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 220.58, 20 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-08-28', 'YYYY-MM-DD'), 9, 20 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-01-04', 'YYYY-MM-DD'), TO_DATE('2019-03-21', 'YYYY-MM-DD'), 8, 20 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-12-01', 'YYYY-MM-DD'), NULL, 10, 20 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 325.29, 21 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 7, 21 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 107.85, 22 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 22 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 722.63, 23 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 9, 23 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 416.69, 24 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 24 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 31.59, 25 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 25 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 250.65, 26 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 9, 26 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 215.59, 27 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2019-05-09', 'YYYY-MM-DD'), 10, 27 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-07-22', 'YYYY-MM-DD'), NULL, 10, 27 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 566.08, 28 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 28 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 688.16, 29 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 29 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 292.16, 30 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-05-31', 'YYYY-MM-DD'), 9, 30 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-08-31', 'YYYY-MM-DD'), TO_DATE('2018-11-27', 'YYYY-MM-DD'), 5, 30 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2020-04-04', 'YYYY-MM-DD'), NULL, 7, 30 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 929.41, 31 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 7, 31 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 173.85, 32 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-05-17', 'YYYY-MM-DD'), 1, 32 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-09-24', 'YYYY-MM-DD'), TO_DATE('2019-10-01', 'YYYY-MM-DD'), 6, 32 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-11-20', 'YYYY-MM-DD'), NULL, 8, 32 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 972.28, 33 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2019-05-20', 'YYYY-MM-DD'), 4, 33 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-05-30', 'YYYY-MM-DD'), NULL, 3, 33 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 295.91, 34 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 34 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 949.38, 35 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 35 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 623.18, 36 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 36 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 553.17, 37 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 37 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 663.05, 38 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 38 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 718.19, 39 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 39 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 888.93, 40 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-07-07', 'YYYY-MM-DD'), 4, 40 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-02-06', 'YYYY-MM-DD'), TO_DATE('2019-03-13', 'YYYY-MM-DD'), 4, 40 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-08-10', 'YYYY-MM-DD'), NULL, 4, 40 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 541.02, 41 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 8, 41 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 644.57, 42 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 42 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 577.86, 43 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 43 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 951.81, 44 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 44 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 886.19, 45 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 45 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 820.07, 46 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 7, 46 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 95.54, 47 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 47 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 591.41, 48 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 48 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 430.7, 49 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 49 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 980.78, 50 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 50 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 934.6, 51 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-11-16', 'YYYY-MM-DD'), 3, 51 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-11-23', 'YYYY-MM-DD'), TO_DATE('2018-12-13', 'YYYY-MM-DD'), 8, 51 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-06-19', 'YYYY-MM-DD'), NULL, 1, 51 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 514.84, 52 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 52 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 554.46, 53 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 53 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 697.03, 54 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2019-01-16', 'YYYY-MM-DD'), 5, 54 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-09-17', 'YYYY-MM-DD'), TO_DATE('2020-04-01', 'YYYY-MM-DD'), 1, 54 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2020-04-08', 'YYYY-MM-DD'), NULL, 2, 54 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 421.56, 55 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 55 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 288.57, 56 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-08-31', 'YYYY-MM-DD'), 7, 56 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-10-06', 'YYYY-MM-DD'), TO_DATE('2019-11-30', 'YYYY-MM-DD'), 5, 56 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2020-04-10', 'YYYY-MM-DD'), NULL, 5, 56 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 517.4, 57 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 57 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2019-01-17', 'YYYY-MM-DD'), 833.26, 58 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2019-01-18', 'YYYY-MM-DD'), NULL, 514.63, 58 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 58 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 377.37, 59 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 59 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 350.77, 60 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 60 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 211.97, 61 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 7, 61 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 314.75, 62 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 62 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 228.65, 63 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 63 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 355.48, 64 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 64 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 943.94, 65 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 9, 65 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 482.28, 66 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 66 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 148.65, 67 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 67 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-10-29', 'YYYY-MM-DD'), 997.45, 68 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-10-30', 'YYYY-MM-DD'), TO_DATE('2019-03-18', 'YYYY-MM-DD'), 794.57, 68 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2019-03-19', 'YYYY-MM-DD'), NULL, 525.3, 68 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 68 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 840.0, 69 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 69 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 769.59, 70 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 7, 70 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 80.26, 71 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 71 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 487.87, 72 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 72 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 378.24, 73 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 73 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 541.59, 74 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 74 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 520.11, 75 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 75 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 667.4, 76 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 76 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 417.01, 77 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 77 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 159.2, 78 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 7, 78 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 78.85, 79 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 79 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 766.34, 80 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 8, 80 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 360.86, 81 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 81 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 285.52, 82 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 82 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 162.0, 83 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 8, 83 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 444.5, 84 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 84 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 706.81, 85 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 85 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 368.98, 86 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 8, 86 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 814.74, 87 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 6, 87 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 261.77, 88 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 4, 88 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 655.64, 89 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 5, 89 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 669.15, 90 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 8, 90 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 250.4, 91 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 91 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 616.65, 92 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 92 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 714.57, 93 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 93 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 963.92, 94 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2019-01-08', 'YYYY-MM-DD'), 2, 94 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2019-04-06', 'YYYY-MM-DD'), TO_DATE('2019-11-24', 'YYYY-MM-DD'), 3, 94 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2020-03-03', 'YYYY-MM-DD'), NULL, 2, 94 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), TO_DATE('2018-08-12', 'YYYY-MM-DD'), 714.09, 95 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-08-13', 'YYYY-MM-DD'), NULL, 805.3, 95 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 3, 95 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 114.96, 96 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 2, 96 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 988.75, 97 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 9, 97 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 526.74, 98 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 1, 98 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 120.31, 99 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 99 );
INSERT INTO promjenausluge (tip, od, do, iznos, Usluga_USL_ID) VALUES ('Cijena', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 168.46, 100 );
INSERT INTO promjenausluge (tip, od, do, GrupaPasmina_GUS_ID, Usluga_USL_ID) VALUES ('Ponuda', TO_DATE('2018-05-12', 'YYYY-MM-DD'), NULL, 10, 100 );
