INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'SHEEPDOGS', 'OVČARSKI PSI', 'OVČARSKI PSI', 1, 1);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'CATTLEDOGS (EXCEPT SWISS CATTLEDOGS)', 'PASTIRSKI PSI (SEM ŠVAJCARSKIH PASTIRSKIH PASA)', 'STOČARSKI PSI (OSIM ŠVICARSKIH STOČARSKIH PASA)', 2, 1);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'PINSCHER AND SCHNAUZER TYPE', 'PINČERI I ŠNAUCERI', 'PINČERI I ŠNAUCERI', 3, 2);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'MOLOSSIAN TYPE', 'MOLOSI', 'MOLOSI', 4, 2);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (3, 'SWISS MOUNTAIN- AND CATTLEDOGS', 'ŠVAJCARSKI PLANINSKI I PASTIRSKI PSI', 'ŠVICARSKI PLANINSKI I STOČARSKI PSI', 5, 2);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'LARGE AND MEDIUM SIZED TERRIERS', 'VELIKI I SREDNJI TERIJERI', 'VELIKI I SREDNJI TERIJERI', 6, 3);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'SMALL SIZED TERRIERS', 'MALI TERIJERI', 'MALI TERIJERI', 7, 3);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (3, 'BULL TYPE TERRIERS', 'BUL TERIJERI', 'BULL TERIJERI', 8, 3);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (4, 'TOY TERRIERS', 'PATULJASTI TERIJERI', 'PATULJASTI TERIJERI', 9, 3);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'NORDIC SLEDGE DOGS', 'NORDIJSKI PSI ZA VUČU SAONICA', 'NORDIJSKI PSI ZA VUČU SAONICA', 10, 5);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'NORDIC HUNTING DOGS', 'NORDIJSKI LOVAČKI PSI', 'NORDIJSKI LOVAČKI PSI', 11, 5);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (3, 'NORDIC WATCHDOGS AND HERDERS', 'NORDIJSKI PSI ČUVARI', 'NORDIJSKI PSI ČUVARI', 12, 5);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (4, 'EUROPEAN SPITZ', 'EUROPSKI ŠPICEVI', 'EUROPSKI ŠPICEVI', 13, 5);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (5, 'ASIAN SPITZ AND RELATED BREEDS', 'AZIJSKI ŠPICEVI I SRODNE VRSTE', 'AZIJSKI ŠPICEVI I SRODNE VRSTE', 14, 5);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (6, 'PRIMITIVE TYPE', 'OSNOVNI TIP', 'OSNOVNI TIP', 15, 5);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (7, 'PRIMITIVE TYPE - HUNTING DOGS', 'PRIMITIVAN TIP - LOVAČKI PSI', 'PRIMITIVAN TIP - LOVAČKI PSI', 16, 5);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'SCENT HOUNDS', 'PRIMITIVAN TIP - LOVAČKI PSI TIPA RIDGEBACK', 'PRIMITIVAN TIP - LOVAČKI PSI TIPA RIDGEBACK', 17, 6);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'LEASH (SCENT) HOUNDS', 'GONIČI', 'GONIČI', 18, 6);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (3, 'RELATED BREEDS', 'TRAGAČI PO KRVI', 'TRAGAČI PO KRVI', 19, 6);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'CONTINENTAL POINTING DOGS', 'KONTINENTALNI PTIČARI', 'KONTINENTALNI PTIČARI', 20, 7);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'BRITISH AND IRISH POINTERS AND SETTERS', 'BRITANSKI I IRSKI SETERI', 'BRITANSKI I IRSKI SETERI', 21, 7);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'RETRIEVERS', 'RETRIVERI', 'RETRIVERI', 22, 8);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'FLUSHING DOGS', 'ŠUNJKAVCI', 'ŠUNJKAVCI', 23, 8);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (3, 'WATER DOGS', 'PSI ZA VODU', 'PSI ZA VODU', 24, 8);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'BICHONS AND RELATED BREEDS', 'BISHONI I SRODNE VRSTE', 'BISHONI I SRODNE VRSTE', 25, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'POODLE', 'PUDLE', 'PUDLE', 26, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (3, 'SMALL BELGIAN DOGS', 'MALI BELGIJSKI PSI', 'MALI BELGIJSKI PSI', 27, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (4, 'HAIRLESS DOGS', 'GOLOKOŽI PSI', 'GOLOKOŽI PSI', 28, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (5, 'TIBETAN BREEDS', 'TIBETANSKI PSI', 'TIBETANSKI PSI', 29, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (6, 'CHIHUAHUENO', 'CHIHUAHUA', 'CHIHUAHUA', 30, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (7, 'ENGLISH TOY SPANIELS', 'ENGLESKI ŠPANIJELI ZA IGRU', 'ENGLESKI ŠPANIJELI ZA IGRU', 31, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (8, 'JAPAN CHIN AND PEKINGESE', 'JAPANSKI ŠPANIJELI I PEKINEZERI', 'JAPANSKI ŠPANIJELI I PEKINEZERI', 32, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (9, 'CONTINENTAL TOY SPANIEL AND OTHERS', 'KONTINENTALNI PATULJASTI ŠPANIJELI', 'KONTINENTALNI PATULJASTI ŠPANIJELI', 33, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (10, 'KROMFOHRLÄNDER', 'KROMFORLENDERI', 'KROMFOHRLÄNDER', 34, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (11, 'SMALL MOLOSSIAN TYPE DOGS', 'MALI DOGOLIKI PSI', 'MALI DOGOLIKI PSI', 35, 9);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (1, 'LONG-HAIRED OR FRINGED SIGHTHOUNDS', 'DUGODLAKI HRTOVI', 'DUGODLAKI HRTOVI', 36, 10);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (2, 'ROUGH-HAIRED SIGHTHOUNDS', 'OŠTRODLAKI HRTOVI', 'OŠTRODLAKI HRTOVI', 37, 10);

INSERT INTO FCI_SEK (RB, NAZIV, SRPSKI_NAZIV, HRVATSKI_NAZIV, FCS_ID, FCI_GR_FCG_ID) 
VALUES (3, 'SHORT-HAIRED SIGHTHOUNDS', 'KRATKODLAKI HRTOVI', 'KRATKODLAKI HRTOVI', 38, 10);